// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llczhyoabkjgdxgdqmqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsY3poeW9hYmtqZ2R4Z2RxbXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDk4MTcsImV4cCI6MjA2MjAyNTgxN30.mesrPOJaSXQx8fzibcaVv1ZI3AQLry7duS0TtF4idk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);